name: tracker_run
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.2.2'

dependencies: 
  dio: ^5.0.3
  http_parser: ^4.0.2
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  google_maps_flutter:
  fluttertoast: ^8.1.1
  geolocator: ^9.0.1
  flutter_json_viewer: ^1.0.1
  flutter_native_timezone: ^2.0.0
  sliding_sheet: ^0.5.2
  syncfusion_flutter_sliders: ^20.3.52
  flutter_datetime_picker: ^1.5.1
  image: ^3.2.2
  flutter_map:
  # location:
  webview_flutter: ^3.0.4
  stop_watch_timer: ^2.0.0
  intl: ^0.17.0
  sqflite: ^2.1.0+1
  http:
  #get name country
  geocoding: ^2.0.5
  permission_handler: ^10.0.2
  location:
  quickalert: ^1.0.0
  #bottom navigation bar custom
  # flutter_background_service: ^2.4.5
  flutter_background: ^1.1.0
  # get size device 19/09
  device_info_plus: ^3.2.3
  #parses Adobe After Effects animations exported as json with Bodymovin and renders 19/09
  lottie: ^1.4.3
  #needed to image processing
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.2
  workmanager: ^0.5.1
  #draw chart
  syncfusion_flutter_charts: ^20.2.50
  #rating feeling
  flutter_rating_bar: ^4.0.1
  #redraw polyline
  polyline_do: ^0.1.0
  #laucher icon
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.0
  percent_indicator: ^4.2.2
  fab_circular_menu: ^1.0.2
  connectivity_plus: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  image_picker: ^0.8.6
  path_provider: ^2.0.2
  provider: ^5.0.0
  flutter: 
    sdk: flutter
  timezone: ^0.9.0
  wave: ^0.2.2
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  uni_links: ^0.5.1
  # firebase_dynamic_links: ^5.0.2
  url_launcher: ^6.1.6
  firebase_core: ^2.1.0
  flutter_local_notifications: ^12.0.3
  uuid: ^3.0.6
  pedometer: ^3.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/finish_image.png"
  image_path_android: "assets/images/finish_image.png"
  image_path_ios: "assets/images/finish_image.png"
  min_sdk_android: 21
  remove_alpha_ios: true

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: ^0.10.0


flutter: 
  uses-material-design: true
#  assets:
#    - assets/
  assets:
      - assets/
      - assets/images/
      - assets/animation/
      - assets/icons/
      - assets/fonts/
  fonts:
    - family: Roboto-Black
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto-Thin
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf

